// Deterministic Xacro generator: real <xacro:macro> inertials computed with
// ${...} expressions, plus a scale property. Processes to valid URDF.
import type { RobotSpecification, Link, Geometry } from "@ttr/robot-schema";
import { num, vec, xmlName } from "./format.ts";
import { generateVisual, generateCollision, generateJoint, generateMaterial, generateInertial, setMeshPackage, setMeshPrefix } from "./generate.ts";

const MACROS = `  <xacro:macro name="box_inertial" params="m x y z ox oy oz">
    <inertial>
      <origin xyz="\${ox} \${oy} \${oz}"/>
      <mass value="\${m}"/>
      <inertia ixx="\${(1.0/12.0)*m*(y*y+z*z)}" ixy="0" ixz="0"
               iyy="\${(1.0/12.0)*m*(x*x+z*z)}" iyz="0" izz="\${(1.0/12.0)*m*(x*x+y*y)}"/>
    </inertial>
  </xacro:macro>
  <xacro:macro name="cyl_inertial" params="m r h ox oy oz">
    <inertial>
      <origin xyz="\${ox} \${oy} \${oz}"/>
      <mass value="\${m}"/>
      <inertia ixx="\${(1.0/12.0)*m*(3*r*r+h*h)}" ixy="0" ixz="0"
               iyy="\${(1.0/12.0)*m*(3*r*r+h*h)}" iyz="0" izz="\${0.5*m*r*r}"/>
    </inertial>
  </xacro:macro>
  <xacro:macro name="sphere_inertial" params="m r ox oy oz">
    <inertial>
      <origin xyz="\${ox} \${oy} \${oz}"/>
      <mass value="\${m}"/>
      <inertia ixx="\${0.4*m*r*r}" ixy="0" ixz="0" iyy="\${0.4*m*r*r}" iyz="0" izz="\${0.4*m*r*r}"/>
    </inertial>
  </xacro:macro>`;

function inertialCall(l: Link): string {
  const g: Geometry = l.geometry;
  if (g.type === "mesh" || g.type === "capsule" || l.inertia || l.origin.rpy.some((v) => v !== 0))
    return generateInertial(l);
  const [ox, oy, oz] = l.origin.xyz.map(num);
  const m = num(l.mass);
  switch (g.type) {
    case "box": return `  <xacro:box_inertial m="${m}" x="${num(g.size[0])}" y="${num(g.size[1])}" z="${num(g.size[2])}" ox="${ox}" oy="${oy}" oz="${oz}"/>`;
    case "cylinder": return `  <xacro:cyl_inertial m="${m}" r="${num(g.radius)}" h="${num(g.length)}" ox="${ox}" oy="${oy}" oz="${oz}"/>`;
    case "sphere": return `  <xacro:sphere_inertial m="${m}" r="${num(g.radius)}" ox="${ox}" oy="${oy}" oz="${oz}"/>`;
  }
}

function xacroLink(l: Link, meshCollisions = false): string {
  const vis = "  " + generateVisual(l).split("\n").join("\n  ");
  const col = "  " + generateCollision(l,meshCollisions).split("\n").join("\n  ");
  return `<link name="${xmlName(l.name)}">\n${vis}\n${col}\n${inertialCall(l)}\n</link>`;
}

export function generateXacro(spec: RobotSpecification, opts: { meshPrefix?: string; meshCollisions?: boolean } = {}): string {
  if (opts.meshPrefix !== undefined) setMeshPrefix(opts.meshPrefix); else setMeshPackage(spec.robot_name);
  const parts: string[] = [];
  parts.push(`<?xml version="1.0"?>`);
  parts.push(`<!-- Generated by text-to-robot. Process with: xacro ${spec.robot_name}.urdf.xacro -->`);
  parts.push(`<robot name="${xmlName(spec.robot_name)}" xmlns:xacro="http://www.ros.org/wiki/xacro">`);
  parts.push(`  <xacro:property name="scale" value="1.0"/>`);
  parts.push(MACROS);
  for (const m of spec.materials) parts.push("  " + generateMaterial(m));
  for (const l of spec.links) parts.push(indentBlock(xacroLink(l,opts.meshCollisions)));
  for (const j of spec.joints) parts.push(indentBlock(generateJoint(j)));
  parts.push(`</robot>`);
  return parts.join("\n") + "\n";
}

function indentBlock(s: string): string {
  return s.split("\n").map((l) => (l ? "  " + l : l)).join("\n");
}
