// Deterministic parametric CAD (OpenSCAD). Each link becomes a printable module;
// the assembly places every part at its forward-kinematics zero pose.
// Run `openscad -o robot.stl robot.scad` to mesh it.
import type { RobotSpecification, Geometry, Link } from "@ttr/robot-schema";
import { safeName } from "@ttr/robot-schema";
import { forwardKinematics, poseToMat } from "@ttr/kinematics";

const n = (x: number) => (Math.abs(x) < 1e-9 ? 0 : +x.toFixed(5));
const mm = (m: number) => n(m * 1000); // OpenSCAD in millimetres

function solid(g: Geometry): string {
  switch (g.type) {
    case "box": return `cube([${mm(g.size[0])}, ${mm(g.size[1])}, ${mm(g.size[2])}], center=true);`;
    case "cylinder": return `cylinder(h=${mm(g.length)}, r=${mm(g.radius)}, center=true, $fn=48);`;
    case "sphere": return `sphere(r=${mm(g.radius)}, $fn=48);`;
    case "capsule": return `hull() { translate([0,0,${mm(g.length / 2)}]) sphere(r=${mm(g.radius)}, $fn=32); translate([0,0,${mm(-g.length / 2)}]) sphere(r=${mm(g.radius)}, $fn=32); }`;
  }
}

function mat4rows(m: number[]): string {
  const scaled = [...m]; scaled[3] = m[3] * 1000; scaled[7] = m[7] * 1000; scaled[11] = m[11] * 1000; // translation to mm
  const r = (i: number) => `[${n(scaled[i])}, ${n(scaled[i + 1])}, ${n(scaled[i + 2])}, ${n(scaled[i + 3])}]`;
  return `[${r(0)}, ${r(4)}, ${r(8)}, ${r(12)}]`;
}

function moduleName(l: Link): string { return "part_" + safeName(l.name); }

export function generateScad(spec: RobotSpecification): string {
  const world = forwardKinematics(spec, {});
  const out: string[] = [];
  out.push(`// ${spec.robot_name} -- parametric CAD generated by text-to-robot`);
  out.push(`// units: millimetres. Mesh with:  openscad -o ${safeName(spec.robot_name)}.stl this_file.scad`);
  out.push(``);
  for (const l of spec.links) {
    out.push(`module ${moduleName(l)}() {  // ${l.role ?? "link"}, mass ${l.mass.toFixed(3)} kg`);
    out.push(`  multmatrix(${mat4rows(poseToMat(l.origin))})`);
    out.push(`    ${solid(l.geometry)}`);
    out.push(`}`);
  }
  out.push(``, `module ${safeName(spec.robot_name)}_assembly() {`);
  for (const l of spec.links) {
    const w = world.get(l.name);
    if (!w) continue;
    out.push(`  multmatrix(${mat4rows(w)}) ${moduleName(l)}();`);
  }
  out.push(`}`, ``, `${safeName(spec.robot_name)}_assembly();`);
  return out.join("\n") + "\n";
}

export type CadFiles = Record<string, string>;

/** Full CAD deliverable: one part file per link + the assembly + a README. */
export function generateCadFiles(spec: RobotSpecification): CadFiles {
  const name = safeName(spec.robot_name);
  const files: CadFiles = {};
  files[`cad/${name}.scad`] = generateScad(spec);
  for (const l of spec.links) {
    files[`cad/parts/${safeName(l.name)}.scad`] =
      `// printable part: ${l.name} (${l.role ?? "link"})\n` +
      `// units: mm. Mesh with: openscad -o ${safeName(l.name)}.stl ${safeName(l.name)}.scad\n` +
      `multmatrix(${mat4rows(poseToMat(l.origin))})\n  ${solid(l.geometry)}\n`;
  }
  files[`cad/README.md`] =
    `# CAD — ${spec.robot_name}\n\nParametric OpenSCAD parts (millimetres).\n\n` +
    `- \`${name}.scad\` — full assembly at the zero pose\n- \`parts/*.scad\` — one printable part per link\n\n` +
    `## Mesh to STL\n\n\`\`\`bash\nopenscad -o ${name}.stl ${name}.scad          # whole assembly\nopenscad -o base_link.stl parts/base_link.scad  # a single part\n\`\`\`\n\n` +
    `Import the STL into your slicer, or the SCAD into any OpenSCAD-compatible CAD tool.\n`;
  return files;
}
