// Generate a complete, buildable ROS 2 (ament_cmake) package as a path->content map.
import type { RobotSpecification, Joint } from "@ttr/robot-schema";
import { safeName } from "@ttr/robot-schema";
import { generateUrdf, generateXacro } from "@ttr/urdf-generator";
import { buildPart, toStlBinary } from "@ttr/mesh";
import { exportMoveIt } from "./moveit.ts";
import { exportGazebo } from "./gazebo.ts";

export type FileMap = Record<string, string | Uint8Array>;

const actuated = (s: RobotSpecification): Joint[] => s.joints.filter((j) => j.type === "revolute" || j.type === "prismatic" || j.type === "continuous");

export function exportRos2Package(spec: RobotSpecification, opts: { ros2_control?: boolean; moveit?: boolean; gazebo?: boolean } = {}): FileMap {
  const pkg = safeName(spec.robot_name);
  const files: FileMap = {};

  files[`${pkg}/package.xml`] = packageXml(pkg);
  files[`${pkg}/CMakeLists.txt`] = cmake(pkg);
  files[`${pkg}/urdf/${pkg}.urdf.xacro`] = generateXacro(spec);
  files[`${pkg}/urdf/${pkg}.urdf`] = generateUrdf(spec);
  files[`${pkg}/launch/display.launch.py`] = displayLaunch(pkg);
  files[`${pkg}/config/joint_limits.yaml`] = jointLimits(spec);
  files[`${pkg}/rviz/${pkg}.rviz`] = rvizConfig();
  let anyMesh = false;
  for (const l of spec.links) { const g = l.geometry; if (g.type === "mesh" && !files[`${pkg}/meshes/${g.file}`]) { files[`${pkg}/meshes/${g.file}`] = toStlBinary(buildPart(g), 1); anyMesh = true; } }
  if (!anyMesh) files[`${pkg}/meshes/.gitkeep`] = "";
  files[`${pkg}/README.md`] = readme(pkg, spec);
  if (opts.ros2_control) {
    files[`${pkg}/config/controllers.yaml`] = controllersYaml(spec);
    files[`${pkg}/config/ros2_control.xacro`] = ros2ControlXacro(spec);
  }
  if (opts.moveit ?? true) Object.assign(files, exportMoveIt(spec));
  if (opts.gazebo ?? true) Object.assign(files, exportGazebo(spec));
  return files;
}

function packageXml(pkg: string): string {
  return `<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>${pkg}</name>
  <version>0.1.0</version>
  <description>Robot description generated by text-to-robot.</description>
  <maintainer email="you@example.com">you</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher_gui</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>moveit_configs_utils</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
`;
}

function cmake(pkg: string): string {
  return `cmake_minimum_required(VERSION 3.8)
project(${pkg})

find_package(ament_cmake REQUIRED)

install(
  DIRECTORY urdf launch config rviz meshes moveit worlds
  DESTINATION share/\${PROJECT_NAME}
)

ament_package()
`;
}

function displayLaunch(pkg: string): string {
  return `# Generated by text-to-robot
import os
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import Command, LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare


def generate_launch_description():
    pkg = "${pkg}"
    share = get_package_share_directory(pkg)
    xacro_file = os.path.join(share, "urdf", pkg + ".urdf.xacro")
    rviz_file = os.path.join(share, "rviz", pkg + ".rviz")

    robot_description = {
        "robot_description": Command(["xacro ", xacro_file])
    }

    return LaunchDescription([
        DeclareLaunchArgument("gui", default_value="true"),
        Node(
            package="robot_state_publisher",
            executable="robot_state_publisher",
            output="screen",
            parameters=[robot_description],
        ),
        Node(
            package="joint_state_publisher_gui",
            executable="joint_state_publisher_gui",
            condition=None,
        ),
        Node(
            package="rviz2",
            executable="rviz2",
            arguments=["-d", rviz_file],
            output="screen",
        ),
    ])
`;
}

function jointLimits(spec: RobotSpecification): string {
  const lines = ["# Generated by text-to-robot", "joint_limits:"];
  for (const j of actuated(spec)) {
    const lo = j.limit?.lower ?? 0, up = j.limit?.upper ?? 0, vel = j.limit?.velocity ?? 1, eff = j.limit?.effort ?? 10;
    lines.push(`  ${j.name}:`);
    lines.push(`    has_position_limits: ${j.type !== "continuous"}`);
    lines.push(`    min_position: ${lo}`);
    lines.push(`    max_position: ${up}`);
    lines.push(`    has_velocity_limits: true`);
    lines.push(`    max_velocity: ${vel}`);
    lines.push(`    has_effort_limits: true`);
    lines.push(`    max_effort: ${eff}`);
  }
  return lines.join("\n") + "\n";
}

function controllersYaml(spec: RobotSpecification): string {
  const joints = actuated(spec).map((j) => `      - ${j.name}`).join("\n");
  return `# Generated by text-to-robot
controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
${joints}
    command_interfaces: [position]
    state_interfaces: [position, velocity]
`;
}

function ros2ControlXacro(spec: RobotSpecification): string {
  const joints = actuated(spec).map((j) =>
    `    <joint name="${j.name}">\n      <command_interface name="position"/>\n      <state_interface name="position"/>\n      <state_interface name="velocity"/>\n    </joint>`).join("\n");
  return `<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <ros2_control name="${safeName(spec.robot_name)}_system" type="system">
    <hardware>
      <plugin>mock_components/GenericSystem</plugin>
    </hardware>
${joints}
  </ros2_control>
</robot>
`;
}

function rvizConfig(): string {
  return `Panels:
  - Class: rviz_common/Displays
    Name: Displays
Visualization Manager:
  Displays:
    - Class: rviz_default_plugins/Grid
      Name: Grid
      Enabled: true
    - Class: rviz_default_plugins/RobotModel
      Name: RobotModel
      Enabled: true
      Description Topic:
        Value: /robot_description
    - Class: rviz_default_plugins/TF
      Name: TF
      Enabled: true
  Global Options:
    Fixed Frame: base_link
  Tools:
    - Class: rviz_default_plugins/Orbit
`;
}

function readme(pkg: string, spec: RobotSpecification): string {
  return `# ${pkg}

Robot description generated by [text-to-robot](https://github.com/megazron/text-to-robot).

- Links: ${spec.links.length}
- Joints: ${spec.joints.length}
${spec.metadata.source_prompt ? `- Prompt: "${spec.metadata.source_prompt}"` : ""}

## Build

\`\`\`bash
# from your ROS 2 workspace root (e.g. ~/ros2_ws)
cp -r ${pkg} src/
colcon build --packages-select ${pkg}
source install/setup.bash
\`\`\`

## Visualize

\`\`\`bash
ros2 launch ${pkg} display.launch.py
\`\`\`

This starts \`robot_state_publisher\`, \`joint_state_publisher_gui\` (sliders) and RViz2.
`;
}
