// Gazebo (gz-sim, "Ignition"/Harmonic) export: a world SDF and a launch file
// that spawns the generated robot from robot_description via ros_gz_sim.
import type { RobotSpecification } from "@ttr/robot-schema";
import { safeName } from "@ttr/robot-schema";

import type { FileMap } from "./export.ts";

export function exportGazebo(spec: RobotSpecification): FileMap {
  const pkg = safeName(spec.robot_name);
  const files: FileMap = {};
  files[`${pkg}/worlds/${pkg}.sdf`] = `<?xml version="1.0" ?>
<sdf version="1.8">
  <world name="${pkg}_world">
    <physics name="1ms" type="ignored"><max_step_size>0.001</max_step_size><real_time_factor>1.0</real_time_factor></physics>
    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-contact-system" name="gz::sim::systems::Contact"/>
    <light type="directional" name="sun">
      <cast_shadows>true</cast_shadows><pose>0 0 10 0 0 0</pose>
      <diffuse>0.9 0.9 0.9 1</diffuse><specular>0.2 0.2 0.2 1</specular>
      <direction>-0.5 0.1 -0.9</direction>
    </light>
    <model name="ground_plane"><static>true</static>
      <link name="link">
        <collision name="collision"><geometry><plane><normal>0 0 1</normal><size>50 50</size></plane></geometry></collision>
        <visual name="visual"><geometry><plane><normal>0 0 1</normal><size>50 50</size></plane></geometry>
          <material><ambient>0.8 0.8 0.8 1</ambient><diffuse>0.8 0.8 0.8 1</diffuse></material></visual>
      </link>
    </model>
  </world>
</sdf>
`;
  files[`${pkg}/launch/gazebo.launch.py`] = `# Generated by text-to-robot -- spawn the robot in Gazebo (gz-sim) via ros_gz
import os
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import Command
from launch_ros.actions import Node


def generate_launch_description():
    pkg = "${pkg}"
    share = get_package_share_directory(pkg)
    xacro_file = os.path.join(share, "urdf", pkg + ".urdf.xacro")
    world = os.path.join(share, "worlds", pkg + ".sdf")
    ros_gz = get_package_share_directory("ros_gz_sim")

    gz = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(os.path.join(ros_gz, "launch", "gz_sim.launch.py")),
        launch_arguments={"gz_args": f"-r {world}"}.items(),
    )
    rsp = Node(package="robot_state_publisher", executable="robot_state_publisher",
               parameters=[{"robot_description": Command(["xacro ", xacro_file]), "use_sim_time": True}])
    spawn = Node(package="ros_gz_sim", executable="create",
                 arguments=["-topic", "robot_description", "-name", pkg, "-z", "0.1"], output="screen")
    bridge = Node(package="ros_gz_bridge", executable="parameter_bridge",
                  arguments=["/clock@rosgraph_msgs/msg/Clock[gz.msgs.Clock"], output="screen")
    return LaunchDescription([gz, rsp, spawn, bridge])
`;
  files[`${pkg}/worlds/README.md`] = `# Gazebo — ${spec.robot_name}

\`\`\`bash
sudo apt install ros-\${ROS_DISTRO}-ros-gz
ros2 launch ${pkg} gazebo.launch.py
\`\`\`

Spawns the robot from \`robot_description\` into \`worlds/${pkg}.sdf\` (ground plane + sun) with a /clock bridge.
Add \`gz_ros2_control\` to drive the joints from ros2_control.
`;
  return files;
}
