// MoveIt 2 configuration export: SRDF planning groups, kinematics, controllers,
// and a move_group launch using moveit_configs_utils. A real starting point,
// generated deterministically from the spec's kinematic chains.
import type { RobotSpecification, Joint } from "@ttr/robot-schema";
import { safeName, findRoot } from "@ttr/robot-schema";

import type { FileMap } from "./export.ts";

/** longest serial chain of non-fixed, non-gripper joints from the root */
function armChain(spec: RobotSpecification): { joints: Joint[]; tip: string } | null {
  const { root } = findRoot(spec); if (!root) return null;
  const kids = new Map<string, Joint[]>();
  for (const j of spec.joints) { if (!kids.has(j.parent)) kids.set(j.parent, []); kids.get(j.parent)!.push(j); }
  const isGrip = (j: Joint) => /finger|gripper|suction/.test(j.child);
  let best: Joint[] = [];
  const walk = (link: string, path: Joint[]) => {
    const next = (kids.get(link) ?? []).filter((j) => !isGrip(j));
    if (!next.length) { if (path.filter((j) => j.type !== "fixed").length > best.filter((j) => j.type !== "fixed").length) best = path; return; }
    for (const j of next) walk(j.child, [...path, j]);
  };
  walk(root, []);
  const moving = best.filter((j) => j.type !== "fixed");
  if (moving.length < 2) return null;
  return { joints: moving, tip: moving[moving.length - 1].child };
}

export function exportMoveIt(spec: RobotSpecification): FileMap {
  const pkg = safeName(spec.robot_name);
  const chain = armChain(spec);
  const files: FileMap = {};
  if (!chain) {
    files[`${pkg}/moveit/README.md`] = `# MoveIt 2\n\nNo serial arm chain with 2+ actuated joints was found in ${spec.robot_name}, so no MoveIt config was generated.\n`;
    return files;
  }
  const { root } = findRoot(spec);
  const gripperJoints = spec.joints.filter((j) => /finger/.test(j.child) && j.type !== "fixed");
  const gripLinks = spec.links.filter((l) => l.role === "gripper").map((l) => l.name);

  files[`${pkg}/moveit/${pkg}.srdf`] = `<?xml version="1.0"?>
<robot name="${pkg}">
  <group name="arm">
    <chain base_link="${root}" tip_link="${chain.tip}"/>
  </group>
${gripLinks.length ? `  <group name="gripper">\n${gripLinks.map((l) => `    <link name="${l}"/>`).join("\n")}\n  </group>\n  <end_effector name="gripper" parent_link="${chain.tip}" group="gripper"/>\n` : ""}  <group_state name="home" group="arm">
${chain.joints.map((j) => `    <joint name="${j.name}" value="0"/>`).join("\n")}
  </group_state>
  <virtual_joint name="world_joint" type="fixed" parent_frame="world" child_link="${root}"/>
${adjacentDisables(spec)}</robot>
`;
  files[`${pkg}/moveit/kinematics.yaml`] = `arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
`;
  files[`${pkg}/moveit/moveit_controllers.yaml`] = `moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
moveit_simple_controller_manager:
  controller_names:
    - joint_trajectory_controller
  joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
${chain.joints.map((j) => `      - ${j.name}`).join("\n")}
`;
  files[`${pkg}/moveit/ompl_planning.yaml`] = `planning_plugins:
  - ompl_interface/OMPLPlanner
arm:
  default_planner_config: RRTConnect
  planner_configs: [RRTConnect, RRTstar, PRM]
`;
  files[`${pkg}/launch/move_group.launch.py`] = `# Generated by text-to-robot -- MoveIt 2 move_group + RViz
from moveit_configs_utils import MoveItConfigsBuilder
from moveit_configs_utils.launches import generate_demo_launch


def generate_launch_description():
    moveit_config = (
        MoveItConfigsBuilder("${pkg}", package_name="${pkg}")
        .robot_description(file_path="urdf/${pkg}.urdf.xacro")
        .robot_description_semantic(file_path="moveit/${pkg}.srdf")
        .robot_description_kinematics(file_path="moveit/kinematics.yaml")
        .trajectory_execution(file_path="moveit/moveit_controllers.yaml")
        .planning_pipelines(pipelines=["ompl"])
        .to_moveit_configs()
    )
    return generate_demo_launch(moveit_config)
`;
  files[`${pkg}/moveit/README.md`] = `# MoveIt 2 — ${spec.robot_name}

Planning group \`arm\`: ${chain.joints.map((j) => j.name).join(" → ")} (tip \`${chain.tip}\`).${gripperJoints.length ? ` End effector group \`gripper\` (${gripperJoints.length} joints).` : ""}

\`\`\`bash
sudo apt install ros-\${ROS_DISTRO}-moveit ros-\${ROS_DISTRO}-moveit-configs-utils
ros2 launch ${pkg} move_group.launch.py     # move_group + RViz MotionPlanning panel
\`\`\`

The SRDF disables collisions between adjacent links; tune it with the MoveIt Setup Assistant if needed.
`;
  return files;
}

function adjacentDisables(spec: RobotSpecification): string {
  return spec.joints.map((j) => `  <disable_collisions link1="${j.parent}" link2="${j.child}" reason="Adjacent"/>`).join("\n") + "\n";
}
